const productAll = [
  {
    id: 1,
    name: "AF12",
    img: require("../../assets/pic1.jpg"),
    des: "Size 48 white",
    price: 189,
    countInStock: 3,
    rating: 4,
    numReviews: 4,
  },
  {
    id: 1,
    name: "AF12",
    img: require("../../assets/pic1.jpg"),
    des: "Size 48 white",
    price: 189,
    countInStock: 3,
    rating: 4,
    numReviews: 4,
  },
  {
    id: 1,
    name: "AF12",
    img: require("../../assets/pic1.jpg"),
    des: "Size 48 white",
    price: 189,
    countInStock: 3,
    rating: 4,
    numReviews: 4,
  },
  {
    id: 1,
    name: "AF12",
    img: require("../../assets/pic1.jpg"),
    des: "Size 48 white",
    price: 189,
    countInStock: 3,
    rating: 4,
    numReviews: 4,
  },
  {
    id: 1,
    name: "AF12",
    img: require("../../assets/pic1.jpg"),
    des: "Size 48 white",
    price: 189,
    countInStock: 3,
    rating: 4,
    numReviews: 4,
  },
];
